#!/usr/bin/env python3
"""Convert an image to the repository's MobileNetV2 input representation.

The actual bundled model input tensor is UINT8 NHWC [1,224,224,3], RGB, with
scale 0.007843137718737125 and zero point 127. Firmware copies these bytes
unchanged into the TFLite input tensor. This utility performs RGB conversion and
a direct 224x224 bilinear resize (no crop), matching mnv2_baseline.
"""

import argparse
import hashlib
from pathlib import Path
from PIL import Image

WIDTH = 224
HEIGHT = 224
CHANNELS = 3
EXPECTED_BYTES = WIDTH * HEIGHT * CHANNELS


def fnv1a(data):
    value = 2166136261
    for byte in data:
        value ^= byte
        value = (value * 16777619) & 0xFFFFFFFF
    return value


def convert(input_path, output_path):
    image = Image.open(input_path).convert("RGB")
    original_size = image.size
    image = image.resize((WIDTH, HEIGHT), Image.Resampling.BILINEAR)
    data = image.tobytes()  # interleaved row-major RGBRGB...
    if len(data) != EXPECTED_BYTES:
        raise RuntimeError(f"generated {len(data)} bytes, expected {EXPECTED_BYTES}")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    guard = "MNV2_CFU_DEPTHWISE_INPUT_IMAGE_H_"
    with output_path.open("w", encoding="utf-8") as handle:
        handle.write(f"#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n\n")
        handle.write("// Generated by tools/image_to_header.py.\n")
        handle.write("// UINT8 NHWC [1,224,224,3], interleaved RGB.\n")
        handle.write("static const unsigned char input_image[] = {\n")
        for offset in range(0, len(data), 16):
            chunk = data[offset:offset + 16]
            handle.write("    " + ", ".join(f"0x{x:02x}" for x in chunk) + ",\n")
        handle.write("};\n\n")
        handle.write(f"static const unsigned int input_image_len = {len(data)};\n")
        handle.write(f"static const unsigned int input_image_width = {WIDTH};\n")
        handle.write(f"static const unsigned int input_image_height = {HEIGHT};\n")
        handle.write(f"static const unsigned int input_image_channels = {CHANNELS};\n\n")
        handle.write(f"#endif  // {guard}\n")

    dat_path = output_path.with_suffix(".dat")
    dat_path.write_bytes(data)
    print(f"Input          : {input_path}")
    print(f"Original size  : {original_size[0]}x{original_size[1]}")
    print("Conversion     : RGB")
    print("Resize         : 224x224 bilinear, stretch, no crop")
    print("Tensor layout  : UINT8 NHWC [1,224,224,3]")
    print("Channel order  : RGB")
    print("Tensor scale   : 0.007843137718737125")
    print("Tensor zero pt : 127")
    print("Normalization  : none in this script; raw 0..255 bytes")
    print(f"Header         : {output_path}")
    print(f"Raw data       : {dat_path}")
    print(f"Bytes          : {len(data)}")
    print(f"SHA256         : {hashlib.sha256(data).hexdigest()}")
    print(f"FNV1a          : 0x{fnv1a(data):08x}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input", help="JPEG/PNG/etc. input image")
    parser.add_argument(
        "output", nargs="?", default="src/input_image.h",
        help="generated header (default: src/input_image.h)")
    args = parser.parse_args()
    convert(args.input, args.output)


if __name__ == "__main__":
    main()
