// AUTO-GENERATED by tools/gen_fused_plan.py from mobilenetv3_small_full_int8.tflite -- do not edit
#pragma once

// op indices count only CONV_2D / DEPTHWISE_CONV_2D / PAD / HARD_SWISH in execution order (-1 = absent)
typedef struct { int e, hs1, pad, d, hs2, mean, mulg, p;  int H, W, N, M, P, K, stride, oh, ow, pad_top, pad_left; } fused_block_t;

static const fused_block_t kFusedBlocks[] = {
  {  10, -1, -1, 11, -1, -1, -1, 12,    56, 56,  16,  72,  24, 3, 2,  28, 28, 0,0 },
  {  13, -1, -1, 14, -1, -1, -1, 15,    28, 28,  24,  88,  24, 3, 1,  28, 28, 0,0 },
  {  16, 17, -1, 18, 19, 20, 24, 25,    28, 28,  24,  96,  32, 5, 2,  14, 14, 0,0 },
  {  26, 27, -1, 28, 29, 30, 34, 35,    14, 14,  32, 192,  32, 5, 1,  14, 14, 0,0 },
  {  36, 37, -1, 38, 39, 40, 44, 45,    14, 14,  32, 192,  32, 5, 1,  14, 14, 0,0 },
  {  46, 47, -1, 48, 49, 50, 54, 55,    14, 14,  32,  96,  40, 5, 1,  14, 14, 0,0 },
  {  56, 57, -1, 58, 59, 60, 64, 65,    14, 14,  40, 120,  40, 5, 1,  14, 14, 0,0 },
  {  66, 67, -1, 68, 69, 70, 74, 75,    14, 14,  40, 240,  72, 5, 2,   7,  7, 0,0 },
  {  76, 77, -1, 78, 79, 80, 84, 85,     7,  7,  72, 432,  72, 5, 1,   7,  7, 0,0 },
  {  86, 87, -1, 88, 89, 90, 94, 95,     7,  7,  72, 432,  72, 5, 1,   7,  7, 0,0 },
};
static const int kNumFusedBlocks = 10;
static const int kNumTrackedOps = 102;
#define FUSED_MAX_F1  225792   /* largest H*W*M   (verify buffers) */
#define FUSED_MAX_F2  68992   /* largest oh*ow*M */
#define FUSED_MAX_OUT 18816   /* largest oh*ow*P (scratch for overlapping output) */
#define FUSED_MAX_IN  50176   /* largest H*W*N   (verify copy of the expansion input) */
