#!/usr/bin/env python3
"""
gen_fused_plan.py -- finds every  CONV_2D(1x1) -> [PAD] -> DEPTHWISE_CONV_2D(3x3) -> CONV_2D(1x1)
inverted-residual block in a TFLite model and writes src/fused_plan.h.

Ops are numbered in execution order, counting only CONV_2D, DEPTHWISE_CONV_2D and PAD (the three
operators the fused-CFU hooks intercept).  The firmware counts the same way at run time.

usage: python3 tools/gen_fused_plan.py model/mobilenetv2_a035_224_int8.tflite src/fused_plan.h
"""
import sys, tflite

def load(path):
    buf = open(path, "rb").read()
    m = tflite.Model.GetRootAsModel(buf, 0)
    g = m.Subgraphs(0)
    names = {v: k for k, v in vars(tflite.BuiltinOperator).items() if not k.startswith("_")}
    codes = []
    for i in range(m.OperatorCodesLength()):
        oc = m.OperatorCodes(i)
        codes.append(max(oc.BuiltinCode(), oc.DeprecatedBuiltinCode()))
    ops = []
    for i in range(g.OperatorsLength()):
        op = g.Operators(i)
        ops.append(dict(i=i, type=names.get(codes[op.OpcodeIndex()], "?"),
                        ins=[op.Inputs(j) for j in range(op.InputsLength())],
                        outs=[op.Outputs(j) for j in range(op.OutputsLength())], op=op))
    return m, g, ops

def main():
    m, g, ops = load(sys.argv[1])
    shape = lambda t: [int(x) for x in g.Tensors(t).ShapeAsNumpy()]
    zp = lambda t: int(g.Tensors(t).Quantization().ZeroPointAsNumpy()[0])
    users = {}
    for o in ops:
        for t in o["ins"]: users[t] = users.get(t, 0) + 1
    tracked = [o for o in ops if o["type"] in ("CONV_2D", "DEPTHWISE_CONV_2D", "PAD")]
    for k, o in enumerate(tracked): o["k"] = k
    byidx = {o["i"]: o for o in ops}

    blocks = []
    i = 0
    while i < len(ops):
        o = ops[i]
        if o["type"] == "CONV_2D" and shape(o["ins"][1])[1:3] == [1, 1]:
            j = i + 1; pad = None
            if j < len(ops) and ops[j]["type"] == "PAD": pad = ops[j]; j += 1
            if j + 1 < len(ops) and ops[j]["type"] == "DEPTHWISE_CONV_2D" and ops[j + 1]["type"] == "CONV_2D":
                d, p = ops[j], ops[j + 1]
                chain = (pad["outs"][0] if pad else o["outs"][0])
                ok = (shape(d["ins"][1])[1:3] == [3, 3] and shape(p["ins"][1])[1:3] == [1, 1]
                      and d["ins"][0] == chain and p["ins"][0] == d["outs"][0]
                      and users.get(o["outs"][0], 0) == 1 and users.get(d["outs"][0], 0) == 1
                      and (pad is None or (pad["ins"][0] == o["outs"][0] and users.get(pad["outs"][0], 0) == 1)))
                if ok:
                    ein, eout = shape(o["ins"][0]), shape(o["outs"][0])
                    dout, pout = shape(d["outs"][0]), shape(p["outs"][0])
                    dopt = tflite.DepthwiseConv2DOptions(); dopt.Init(d["op"].BuiltinOptions().Bytes, d["op"].BuiltinOptions().Pos)
                    assert dopt.DepthMultiplier() == 1 and dopt.StrideH() == dopt.StrideW()
                    stride = dopt.StrideH()
                    if pad is not None:
                        assert zp(pad["outs"][0]) == zp(o["outs"][0]), "PAD zero-point must equal expansion output zero-point"
                        # the paddings constant must be [[0,0],[0,1],[0,1],[0,0]] (bottom/right 1) and the depthwise VALID
                        import numpy as np
                        pt = g.Tensors(pad["ins"][1]); raw = m.Buffers(pt.Buffer()).DataAsNumpy()
                        pads = np.frombuffer(raw.tobytes(), dtype=np.int32).reshape(4, 2).tolist()
                        assert pads == [[0, 0], [0, 1], [0, 1], [0, 0]], "unsupported PAD amounts: %s" % pads
                        assert dopt.Padding() == tflite.Padding.VALID, "depthwise after PAD must be VALID"
                        assert shape(d["ins"][0])[1] == ein[1] + 1
                    if pad is None:
                        assert dopt.Padding() == tflite.Padding.SAME and stride == 1, "unpadded block must be stride-1 SAME"
                    blocks.append(dict(e=o["k"], pad=(pad["k"] if pad else -1), d=d["k"], p=p["k"],
                                       H=ein[1], W=ein[2], N=ein[3], M=eout[3], P=pout[3],
                                       stride=stride, oh=pout[1], ow=pout[2], padded=pad is not None))
                    i = j + 2; continue
        i += 1

    with open(sys.argv[2], "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_fused_plan.py from %s -- do not edit\n" % sys.argv[1].split("/")[-1])
        f.write("#pragma once\n\n// op indices count only CONV_2D / DEPTHWISE_CONV_2D / PAD in execution order\n")
        f.write("typedef struct { int e, pad, d, p;  int H, W, N, M, P, stride, oh, ow; } fused_block_t;\n\n")
        f.write("static const fused_block_t kFusedBlocks[] = {\n")
        for b in blocks:
            f.write("  { %3d, %3d, %3d, %3d,   %3d,%3d,%4d,%4d,%4d, %d, %3d,%3d },\n" %
                    (b["e"], b["pad"], b["d"], b["p"], b["H"], b["W"], b["N"], b["M"], b["P"], b["stride"], b["oh"], b["ow"]))
        f.write("};\nstatic const int kNumFusedBlocks = %d;\nstatic const int kNumTrackedOps = %d;\n" % (len(blocks), len(tracked)))
    print("model ops=%d tracked=%d  fusable blocks=%d" % (len(ops), len(tracked), len(blocks)))
    for n, b in enumerate(blocks):
        print("  block %2d  ops E=%2d%s D=%2d P=%2d   %3dx%3dx%-3d -> M=%3d -> %3dx%3dx%-3d  s%d" %
              (n, b["e"], (" PAD=%2d" % b["pad"]) if b["padded"] else "       ", b["d"], b["p"], b["H"], b["W"], b["N"], b["M"], b["oh"], b["ow"], b["P"], b["stride"]))

main()
