#!/usr/bin/env python3
"""
webcam_classifier.py -- webcam -> MobileNetV2 on the fused-CFU FPGA board -> result, once a minute.

When started it opens the camera, then every INTERVAL seconds (default 60):
  1. grabs the newest frame,
  2. converts it exactly like tools/image_to_header.py of the other projects (RGB, 224x224, bilinear),
  3. saves   <stamp>.jpg   the frame,
             <stamp>.dat   raw 224*224*3 RGB bytes  (the "dat" file),
             <stamp>.h     C header (array name cat_image, drop-in for the other projects' src/cat_image.h),
  4. sends the raw bytes to the board over the UART (checksummed), the board runs MobileNetV2 on the fused CFU,
  5. prints top-1 / top-5 with class names and the cycle counts, and appends a line to results.csv.

Typical use (board already programmed and the firmware loaded, see README.md):
    python3 webcam_classifier.py --port /dev/ttyUSB2
Without a board (PC simulation: real TFLM + the real RTL through Verilator):
    python3 webcam_classifier.py --sim --image ../inputs/cat.jpg --count 1
"""
import argparse, csv, datetime, json, os, queue, re, struct, subprocess, sys, threading, time
import numpy as np
from PIL import Image

W = H = 224
NBYTES = W * H * 3
HERE = os.path.dirname(os.path.abspath(__file__))


# ----------------------------------------------------------------------------- image conversion
def fnv1a(data):
    h = 2166136261
    for b in data:
        h = ((h ^ b) * 16777619) & 0xFFFFFFFF
    return h


def to_model_input(rgb, center_crop=False):
    """rgb: HxWx3 uint8 (RGB).  Same preprocessing as tools/image_to_header.py: plain bilinear resize to 224x224
    (optionally after a centre square crop).  Returns the 150528 raw bytes."""
    img = Image.fromarray(rgb)
    if center_crop:
        w, h = img.size
        s = min(w, h)
        img = img.crop(((w - s) // 2, (h - s) // 2, (w - s) // 2 + s, (h - s) // 2 + s))
    img = img.resize((W, H), Image.Resampling.BILINEAR)
    data = np.asarray(img, dtype=np.uint8).tobytes()
    assert len(data) == NBYTES
    return data


def save_capture(base, frame_rgb, data):
    Image.fromarray(frame_rgb).save(base + ".jpg", quality=92)
    with open(base + ".dat", "wb") as f:
        f.write(data)
    with open(base + ".h", "w") as f:               # same layout as src/cat_image.h of the other projects
        f.write("// Auto-generated by webcam_classifier.py: %s\n" % os.path.basename(base))
        f.write("// 224 x 224 x 3, RGB, UINT8, row-major\n")
        f.write("static const unsigned char cat_image[] = {\n")
        for i in range(0, len(data), 16):
            f.write("  " + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",\n")
        f.write("};\nstatic const unsigned int cat_image_len = %d;\n" % len(data))


# ----------------------------------------------------------------------------- transports
class SerialTransport:
    def __init__(self, port, baud):
        import serial
        self.ser = serial.Serial(port, baud, timeout=0.2)

    def write(self, b):
        self.ser.write(b)

    def read_chunk(self):
        return self.ser.read(4096)           # b"" on timeout

    def close(self):
        self.ser.close()


class ProcTransport:
    """The PC simulation: host_mnv2 --serve speaks the same protocol on stdin/stdout."""
    def __init__(self, cmd):
        self.p = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, bufsize=0)

    def write(self, b):
        self.p.stdin.write(b)
        self.p.stdin.flush()

    def read_chunk(self):
        return os.read(self.p.stdout.fileno(), 4096)   # b"" = EOF

    def close(self):
        try:
            self.p.stdin.close()
        except Exception:
            pass
        try:
            self.p.wait(timeout=5)
        except Exception:
            self.p.kill()


class BoardLink:
    def __init__(self, transport, verbose=False):
        self.t = transport
        self.q = queue.Queue()
        self.verbose = verbose
        self.alive = True
        threading.Thread(target=self._reader, daemon=True).start()

    def _reader(self):
        buf = b""
        while self.alive:
            try:
                chunk = self.t.read_chunk()
            except Exception:
                break
            if chunk == b"" and isinstance(self.t, ProcTransport):
                break
            buf += chunk
            while b"\n" in buf:
                line, buf = buf.split(b"\n", 1)
                self.q.put(line.decode("utf-8", "replace").rstrip("\r"))
        self.q.put(None)

    def _get(self, timeout):
        try:
            return self.q.get(timeout=timeout)
        except queue.Empty:
            return ""

    def drain(self):
        try:
            while True:
                self.q.get_nowait()
        except queue.Empty:
            pass

    def wait_ready(self, timeout=120, auto_menu=True):
        """Ping until the firmware answers '@@READY'.  If the board sits at the CFU-Playground main menu,
        key '3' (project menu) starts the firmware's image server."""
        t0 = time.time()
        sent_menu = False
        last_ping = 0
        while time.time() - t0 < timeout:
            if time.time() - last_ping > 2.0:
                if auto_menu and not sent_menu and time.time() - t0 > 3.0:
                    self.t.write(b"3")
                    sent_menu = True
                self.t.write(b"IMG?")
                last_ping = time.time()
            line = self._get(0.2)
            if line is None:
                raise RuntimeError("board/simulator closed the connection")
            if self.verbose and line:
                print("   board>", line)
            if line.startswith("@@READY"):
                self.drain()
                return line
        raise TimeoutError("no '@@READY' from the board (is the firmware loaded and running?)")

    def classify(self, payload, ack_timeout=60, result_timeout=1800, progress=None):
        frame = b"IMG!" + struct.pack("<I", len(payload)) + payload + struct.pack("<I", fnv1a(payload))
        for attempt in range(3):
            self.drain()
            t0 = time.time()
            for i in range(0, len(frame), 1024):
                self.t.write(frame[i:i + 1024])
                if progress:
                    progress(min(i + 1024, len(frame)), len(frame))
            send_s = time.time() - t0
            verdict = None
            t1 = time.time()
            while time.time() - t1 < ack_timeout:
                line = self._get(0.5)
                if line is None:
                    raise RuntimeError("connection closed")
                if line.startswith("@@ACK"):
                    verdict = "ack"; break
                if line.startswith("@@NAK"):
                    verdict = line; break
            if verdict == "ack":
                break
            print("   transfer failed (%s), retry %d/3" % (verdict or "no answer", attempt + 1))
        else:
            raise RuntimeError("image transfer failed 3 times")

        res = {"send_s": send_s, "profile": [], "fused": None, "cycles": None, "top5": [], "logits": None}
        t2 = time.time()
        while time.time() - t2 < result_timeout:
            line = self._get(1.0)
            if line is None:
                raise RuntimeError("connection closed during inference")
            if not line:
                continue
            if line.startswith("@@END"):
                res["infer_s"] = time.time() - t2
                return res
            if line.startswith("@@RESULT"):
                m = dict(re.findall(r"(\w+)=(-?\w+)", line))
                res["top1"] = int(m["top1"]); res["score_e6"] = int(m["score_e6"])
            elif line.startswith("@@TOP5"):
                res["top5"] = [tuple(int(x) for x in p.split(":")) for p in line.split()[1:]]
            elif line.startswith("@@LOGITS_E6"):
                res["logits"] = [int(x) for x in line.split(" ", 1)[1].split(",")]
            elif line.startswith("@@FUSED"):
                res["fused"] = {k: int(v) for k, v in re.findall(r"(\w+)=(\d+)", line)}
            else:
                m = re.search(r"\(\s*(\d+)\s*\)\s*cycles total", line)
                if m:
                    res["cycles"] = int(m.group(1))
                res["profile"].append(line)
                if self.verbose:
                    print("   board>", line)
        raise TimeoutError("no '@@END' from the board")

    def close(self):
        self.alive = False
        self.t.close()


# ----------------------------------------------------------------------------- frame sources
class CameraSource:
    """Opens the camera at start-up and keeps pulling frames so the newest one is always fresh."""
    def __init__(self, device, warmup=15):
        import cv2
        self.cv2 = cv2
        dev = int(device) if str(device).isdigit() else device
        self.cap = cv2.VideoCapture(dev)
        if not self.cap.isOpened():
            raise RuntimeError("cannot open camera %r (try --camera 1, or check permissions / other programs using it)" % (device,))
        self.last = None
        for _ in range(warmup):                 # let auto-exposure settle
            self.pump()
            time.sleep(0.05)

    def pump(self):
        ok, f = self.cap.read()
        if not ok:                              # end of a video file used as a fake camera -> loop
            self.cap.set(self.cv2.CAP_PROP_POS_FRAMES, 0)
            ok, f = self.cap.read()
        if ok:
            self.last = f
        return self.last

    def latest_rgb(self):
        for _ in range(3):
            self.pump()
        if self.last is None:
            raise RuntimeError("camera returned no frame")
        return self.cv2.cvtColor(self.last, self.cv2.COLOR_BGR2RGB)

    def preview_bgr(self):
        return self.last

    def close(self):
        self.cap.release()


class ImageSource:
    """Cycles through image files (testing without a camera)."""
    def __init__(self, paths):
        self.paths = paths
        self.i = 0

    def pump(self):
        return None

    def latest_rgb(self):
        p = self.paths[self.i % len(self.paths)]
        self.i += 1
        return np.asarray(Image.open(p).convert("RGB"), dtype=np.uint8)

    def preview_bgr(self):
        return None

    def close(self):
        pass


# ----------------------------------------------------------------------------- reporting
def load_labels(path):
    labels = {}
    try:
        for line in open(path):
            m = re.match(r"\s*(\d+)\s*:\s*(.*)", line)
            if m:
                labels[int(m.group(1))] = m.group(2).strip()
    except OSError:
        pass
    return labels


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--port", help="serial port of the board, e.g. /dev/ttyUSB2 or COM5 (default: auto)")
    ap.add_argument("--baud", type=int, default=115200)
    ap.add_argument("--camera", default="0", help="camera index or video file (default 0)")
    ap.add_argument("--interval", type=float, default=60.0, help="seconds between pictures (default 60)")
    ap.add_argument("--first-delay", type=float, default=3.0, help="seconds before the first picture (default 3)")
    ap.add_argument("--count", type=int, default=0, help="stop after N pictures (default: run until Ctrl-C)")
    ap.add_argument("--out-dir", default="captures", help="where .jpg/.dat/.h/results.csv are written")
    ap.add_argument("--center-crop", action="store_true", help="centre-crop to a square before resizing")
    ap.add_argument("--image", action="append", help="use image file(s) instead of the camera (repeatable)")
    ap.add_argument("--image-dir", help="use all images of a directory instead of the camera")
    ap.add_argument("--no-preview", action="store_true", help="do not open the preview window")
    ap.add_argument("--no-auto-menu", action="store_true", help="do not press '3' for the project menu automatically")
    ap.add_argument("--labels", default=os.path.join(HERE, "labels.txt"))
    ap.add_argument("--no-send", action="store_true", help="only capture and convert (no board needed)")
    ap.add_argument("--sim", action="store_true", help="PC simulation instead of a board (real TFLM + RTL via Verilator)")
    ap.add_argument("--sim-bin", default=os.path.join(HERE, "..", "build_host", "vl", "host_mnv2"))
    ap.add_argument("--sim-model", default=os.path.join(HERE, "..", "model", "mobilenetv2_a035_224_int8.tflite"))
    ap.add_argument("--sim-plain", action="store_true", help="simulation without the fused CFU (plain TFLM)")
    ap.add_argument("--verbose", action="store_true", help="echo everything the board prints")
    a = ap.parse_args()

    os.makedirs(a.out_dir, exist_ok=True)
    labels = load_labels(a.labels)

    # ---- frame source: the camera opens right now
    if a.image or a.image_dir:
        paths = list(a.image or [])
        if a.image_dir:
            paths += sorted(os.path.join(a.image_dir, f) for f in os.listdir(a.image_dir)
                            if f.lower().endswith((".jpg", ".jpeg", ".png", ".bmp")))
        if not paths:
            sys.exit("no images found")
        src = ImageSource(paths)
        print("Using %d image file(s) instead of a camera." % len(paths))
    else:
        print("Opening camera %s ..." % a.camera)
        try:
            src = CameraSource(a.camera)
        except RuntimeError as e:
            sys.exit("ERROR: %s" % e)
        print("Camera is open.")

    # ---- board (or simulation)
    link = None
    if not a.no_send:
        if a.sim:
            cmd = [os.path.abspath(a.sim_bin), os.path.abspath(a.sim_model), "--serve", "--fused", "0" if a.sim_plain else "1"]
            print("Starting PC simulation:", " ".join(cmd))
            link = BoardLink(ProcTransport(cmd), a.verbose)
        else:
            port = a.port
            if not port:
                from serial.tools import list_ports
                cand = sorted(p.device for p in list_ports.comports() if "USB" in p.device.upper() or "COM" in p.device.upper())
                if not cand:
                    sys.exit("no serial port found - pass --port")
                port = cand[-1]
                print("Auto-selected serial port %s (candidates: %s)" % (port, ", ".join(cand)))
            link = BoardLink(SerialTransport(port, a.baud), a.verbose)
        print("Waiting for the board ...")
        print("Board says:", link.wait_ready(auto_menu=not a.no_auto_menu))

    preview = not a.no_preview and isinstance(src, CameraSource)
    status = "starting"
    csv_path = os.path.join(a.out_dir, "results.csv")
    new_csv = not os.path.exists(csv_path)
    n = 0
    next_t = time.monotonic() + a.first_delay
    try:
        while True:
            while time.monotonic() < next_t:         # wait, keeping the camera buffer fresh
                src.pump()
                if preview:
                    try:
                        fr = src.preview_bgr()
                        if fr is not None:
                            import cv2
                            fr = fr.copy()
                            cv2.putText(fr, "next shot in %ds | %s" % (max(0, int(next_t - time.monotonic())), status),
                                        (10, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
                            cv2.imshow("fused-CFU MobileNetV2 (q = quit)", fr)
                            if (cv2.waitKey(30) & 0xFF) in (ord("q"), 27):
                                raise KeyboardInterrupt
                    except KeyboardInterrupt:
                        raise
                    except Exception:
                        preview = False
                        print("(preview window not available - continuing without it)")
                else:
                    time.sleep(0.1)

            t_start = time.monotonic()
            stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            base = os.path.join(a.out_dir, stamp)
            rgb = src.latest_rgb()
            data = to_model_input(rgb, a.center_crop)
            save_capture(base, rgb, data)
            n += 1
            print("\n[%s] picture #%d  ->  %s.{jpg,dat,h}   (RGB FNV1a 0x%08x)" %
                  (datetime.datetime.now().strftime("%H:%M:%S"), n, base, fnv1a(data)))

            row = dict(timestamp=stamp, picture=n, image=base + ".dat")
            if link:
                def prog(done, total, _last=[0]):
                    if done * 10 // total != _last[0]:
                        _last[0] = done * 10 // total
                        print("   sending %3d%%" % (done * 100 // total), end="\r", flush=True)
                try:
                    status = "board busy"
                    r = link.classify(data, progress=prog)
                    t = r["top5"][0][0] if r["top5"] else r["top1"]
                    name = labels.get(r["top1"], "class %d" % r["top1"])
                    print("   sent in %.1f s, inference+reply %.1f s" % (r["send_s"], r["infer_s"]))
                    print("   >>> TOP-1: %d  %s   (score %.6f)" % (r["top1"], name, r["score_e6"] / 1e6))
                    for i, (idx, sc) in enumerate(r["top5"]):
                        print("       #%d  %4d  %-28s %.6f" % (i + 1, idx, labels.get(idx, "?"), sc / 1e6))
                    if r["cycles"]:
                        print("   whole-model cycles : {:,}   (= {:.1f} ms at 75 MHz)".format(r["cycles"], r["cycles"] / 75e3))
                    if r["fused"]:
                        f = r["fused"]
                        print("   fused CFU          : %d/16 blocks, CFU busy %s cycles, fused-path CPU %s cycles" %
                              (f.get("blocks", 0), "{:,}".format(f.get("hw_cycles", 0)), "{:,}".format(f.get("cpu_cycles", 0))))
                    row.update(top1=r["top1"], label=name, score=r["score_e6"] / 1e6, cycles=r["cycles"],
                               fused_blocks=(r["fused"] or {}).get("blocks"), fused_hw_cycles=(r["fused"] or {}).get("hw_cycles"),
                               fused_cpu_cycles=(r["fused"] or {}).get("cpu_cycles"), send_s=round(r["send_s"], 1))
                    with open(base + ".json", "w") as jf:
                        json.dump({k: v for k, v in r.items() if k != "profile"}, jf)
                    status = "last: %s %.2f" % (name, r["score_e6"] / 1e6)
                except (TimeoutError, RuntimeError) as e:
                    print("   ERROR:", e)
                    status = "error"
                    row.update(label="ERROR: %s" % e)
                    if isinstance(e, RuntimeError) and "closed" in str(e):
                        break
            with open(csv_path, "a", newline="") as cf:
                cols = ["timestamp", "picture", "image", "top1", "label", "score", "cycles", "fused_blocks",
                        "fused_hw_cycles", "fused_cpu_cycles", "send_s"]
                w = csv.DictWriter(cf, fieldnames=cols)
                if new_csv:
                    w.writeheader(); new_csv = False
                w.writerow({c: row.get(c, "") for c in cols})
            if a.count and n >= a.count:
                break
            next_t = max(next_t + a.interval, time.monotonic() + 0.5)
    except KeyboardInterrupt:
        print("\nStopped by user.")
    finally:
        src.close()
        if link:
            link.close()
        try:
            import cv2
            cv2.destroyAllWindows()
        except Exception:
            pass
    print("Done. Results: %s" % csv_path)


if __name__ == "__main__":
    main()
